/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * WaterJarsGUI.java
 *
 * Created on 19-dic-2011, 18:31:55
 */
package example_waterjars;

import java.awt.event.ActionListener;

/**
 *
 * @author BigEma
 */
public class WaterJarsGUI extends javax.swing.JFrame implements ActionListener {

    /** Creates new form WaterJarsGUI */
    public WaterJarsGUI() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jar1Panel = new javax.swing.JPanel();
        jar1Capacity = new javax.swing.JLabel();
        jar1Ocuppied = new javax.swing.JLabel();
        jar1FillButton = new javax.swing.JButton();
        jar1EmptyButton = new javax.swing.JButton();
        jar1TransferButton = new javax.swing.JButton();
        jar2Panel = new javax.swing.JPanel();
        jar2Capacity = new javax.swing.JLabel();
        jar2Ocuppied = new javax.swing.JLabel();
        jar2FillButton = new javax.swing.JButton();
        jar2EmptyButton = new javax.swing.JButton();
        jar2TransferButton = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        newMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        preferencesMenu = new javax.swing.JMenu();
        estadoInicialMenuItem = new javax.swing.JMenuItem();
        iaMenuItem = new javax.swing.JMenuItem();
        iaMenu = new javax.swing.JMenu();
        clueMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(420, 350));
        setResizable(false);

        jar1Panel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Jarra 1"));
        jar1Panel.setMaximumSize(new java.awt.Dimension(200, 300));
        jar1Panel.setMinimumSize(new java.awt.Dimension(200, 300));
        jar1Panel.setPreferredSize(new java.awt.Dimension(200, 300));

        jar1Capacity.setText("capacidad: ");

        jar1Ocuppied.setText("ocupado: ");

        jar1FillButton.setText("llenar");

        jar1EmptyButton.setText("vaciar");

        jar1TransferButton.setText("transferir");

        javax.swing.GroupLayout jar1PanelLayout = new javax.swing.GroupLayout(jar1Panel);
        jar1Panel.setLayout(jar1PanelLayout);
        jar1PanelLayout.setHorizontalGroup(
            jar1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jar1PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jar1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jar1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jar1Capacity)
                        .addComponent(jar1TransferButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jar1EmptyButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jar1FillButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jar1Ocuppied))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        jar1PanelLayout.setVerticalGroup(
            jar1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jar1PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jar1Capacity)
                .addGap(18, 18, 18)
                .addComponent(jar1Ocuppied)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addComponent(jar1TransferButton)
                .addGap(18, 18, 18)
                .addComponent(jar1EmptyButton)
                .addGap(18, 18, 18)
                .addComponent(jar1FillButton)
                .addContainerGap())
        );

        jar2Panel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Jarra 2"));
        jar2Panel.setMaximumSize(new java.awt.Dimension(200, 300));
        jar2Panel.setMinimumSize(new java.awt.Dimension(200, 300));
        jar2Panel.setPreferredSize(new java.awt.Dimension(200, 300));

        jar2Capacity.setText("capacidad: ");

        jar2Ocuppied.setText("ocupado: ");

        jar2FillButton.setText("llenar");

        jar2EmptyButton.setText("vaciar");

        jar2TransferButton.setText("transferir");

        javax.swing.GroupLayout jar2PanelLayout = new javax.swing.GroupLayout(jar2Panel);
        jar2Panel.setLayout(jar2PanelLayout);
        jar2PanelLayout.setHorizontalGroup(
            jar2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jar2PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jar2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jar2Capacity)
                    .addComponent(jar2Ocuppied))
                .addContainerGap(123, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jar2PanelLayout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addGroup(jar2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jar2FillButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jar2EmptyButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jar2TransferButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jar2PanelLayout.setVerticalGroup(
            jar2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jar2PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jar2Capacity)
                .addGap(18, 18, 18)
                .addComponent(jar2Ocuppied)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addComponent(jar2TransferButton)
                .addGap(18, 18, 18)
                .addComponent(jar2EmptyButton)
                .addGap(18, 18, 18)
                .addComponent(jar2FillButton)
                .addContainerGap())
        );

        fileMenu.setMnemonic('j');
        fileMenu.setText("Jarras");

        newMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        newMenuItem.setMnemonic('n');
        newMenuItem.setText("Nuevo");
        fileMenu.add(newMenuItem);

        exitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        exitMenuItem.setMnemonic('s');
        exitMenuItem.setText("Salir");
        exitMenuItem.addActionListener(this);
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        preferencesMenu.setMnemonic('p');
        preferencesMenu.setText("Preferencias");

        estadoInicialMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        estadoInicialMenuItem.setMnemonic('e');
        estadoInicialMenuItem.setText("Estado inicial");
        preferencesMenu.add(estadoInicialMenuItem);

        iaMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        iaMenuItem.setMnemonic('f');
        iaMenuItem.setText("Preferencias IA");
        preferencesMenu.add(iaMenuItem);

        menuBar.add(preferencesMenu);

        iaMenu.setMnemonic('i');
        iaMenu.setText("IA");

        clueMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        clueMenuItem.setMnemonic('p');
        clueMenuItem.setText("Pista");
        iaMenu.add(clueMenuItem);

        menuBar.add(iaMenu);

        helpMenu.setMnemonic('a');
        helpMenu.setText("Ayuda");

        aboutMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("Acerca de");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jar1Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jar2Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jar2Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
            .addComponent(jar1Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
        );

        pack();
    }

    // Code for dispatching events from components to event handlers.

    public void actionPerformed(java.awt.event.ActionEvent evt) {
        if (evt.getSource() == exitMenuItem) {
            WaterJarsGUI.this.exitMenuItemActionPerformed(evt);
        }
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WaterJarsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WaterJarsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WaterJarsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WaterJarsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new WaterJarsGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem clueMenuItem;
    private javax.swing.JMenuItem estadoInicialMenuItem;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenu iaMenu;
    private javax.swing.JMenuItem iaMenuItem;
    private javax.swing.JLabel jar1Capacity;
    private javax.swing.JButton jar1EmptyButton;
    private javax.swing.JButton jar1FillButton;
    private javax.swing.JLabel jar1Ocuppied;
    private javax.swing.JPanel jar1Panel;
    private javax.swing.JButton jar1TransferButton;
    private javax.swing.JLabel jar2Capacity;
    private javax.swing.JButton jar2EmptyButton;
    private javax.swing.JButton jar2FillButton;
    private javax.swing.JLabel jar2Ocuppied;
    private javax.swing.JPanel jar2Panel;
    private javax.swing.JButton jar2TransferButton;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem newMenuItem;
    private javax.swing.JMenu preferencesMenu;
    // End of variables declaration//GEN-END:variables
}
