/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GaroePlaygroundGUI.java
 *
 * Created on 02-dic-2011, 11:52:21
 */
package examples;

import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import javax.swing.ImageIcon;

/**
 *
 * @author BigEma
 */
public class GaroePlaygroundGUI extends javax.swing.JFrame implements MouseListener, ActionListener {
    private GaroePlaygroundController controller;
    
    /** Creates new form GaroePlaygroundGUI */
    public GaroePlaygroundGUI() {
        initComponents();
    }

    public void setController(GaroePlaygroundController controller) {
        this.controller = controller;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gamesPanel = new javax.swing.JPanel();
        reversi = new javax.swing.JButton();
        floodit = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        gameImage = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        gameInfo = new javax.swing.JTextPane();
        menuBar = new javax.swing.JMenuBar();
        helpMenu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();
        exitButton = new javax.swing.JMenuItem();
        lookNfeel = new javax.swing.JMenu();
        metalMenuItem = new javax.swing.JMenuItem();
        nimbusMenuItem = new javax.swing.JMenuItem();
        cdemotifMenuItem = new javax.swing.JMenuItem();
        windowsMenuItem = new javax.swing.JMenuItem();
        winclassicMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        gamesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("juegos"));

        reversi.setText("Reversi");
        reversi.addMouseListener(this);
        reversi.addActionListener(this);

        floodit.setText("Floodit");
        floodit.addMouseListener(this);
        floodit.addActionListener(this);

        jButton1.setText("Jarras");
        jButton1.addMouseListener(this);
        jButton1.addActionListener(this);

        javax.swing.GroupLayout gamesPanelLayout = new javax.swing.GroupLayout(gamesPanel);
        gamesPanel.setLayout(gamesPanelLayout);
        gamesPanelLayout.setHorizontalGroup(
            gamesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gamesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(gamesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(floodit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(reversi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        gamesPanelLayout.setVerticalGroup(
            gamesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gamesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(reversi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(floodit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(328, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("información del juego"));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("imagenes"));
        jPanel2.setMaximumSize(new java.awt.Dimension(200, 200));
        jPanel2.setMinimumSize(new java.awt.Dimension(200, 200));
        jPanel2.setPreferredSize(new java.awt.Dimension(200, 200));

        gameImage.setMaximumSize(new java.awt.Dimension(200, 200));
        gameImage.setMinimumSize(new java.awt.Dimension(200, 200));
        gameImage.setPreferredSize(new java.awt.Dimension(200, 200));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gameImage, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(gameImage, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("info"));

        gameInfo.setEditable(false);
        gameInfo.setAutoscrolls(false);
        gameInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(gameInfo);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        helpMenu.setMnemonic('h');
        helpMenu.setText("GaroePlayground");

        aboutMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("Acerca de");
        aboutMenuItem.addActionListener(this);
        helpMenu.add(aboutMenuItem);

        exitButton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        exitButton.setMnemonic('x');
        exitButton.setText("Salir");
        exitButton.addActionListener(this);
        helpMenu.add(exitButton);

        menuBar.add(helpMenu);

        lookNfeel.setText("Pieles");

        metalMenuItem.setText("Metal");
        metalMenuItem.addActionListener(this);
        lookNfeel.add(metalMenuItem);

        nimbusMenuItem.setText("Nimbus");
        nimbusMenuItem.addActionListener(this);
        lookNfeel.add(nimbusMenuItem);

        cdemotifMenuItem.setText("CDE/Motif");
        cdemotifMenuItem.addActionListener(this);
        lookNfeel.add(cdemotifMenuItem);

        windowsMenuItem.setText("Windows");
        windowsMenuItem.addActionListener(this);
        lookNfeel.add(windowsMenuItem);

        winclassicMenuItem.setText("Windows Classic");
        winclassicMenuItem.addActionListener(this);
        lookNfeel.add(winclassicMenuItem);

        menuBar.add(lookNfeel);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gamesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gamesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }

    // Code for dispatching events from components to event handlers.

    public void actionPerformed(java.awt.event.ActionEvent evt) {
        if (evt.getSource() == reversi) {
            GaroePlaygroundGUI.this.reversiActionPerformed(evt);
        }
        else if (evt.getSource() == floodit) {
            GaroePlaygroundGUI.this.flooditActionPerformed(evt);
        }
        else if (evt.getSource() == aboutMenuItem) {
            GaroePlaygroundGUI.this.aboutMenuItemActionPerformed(evt);
        }
        else if (evt.getSource() == exitButton) {
            GaroePlaygroundGUI.this.exitButtonActionPerformed(evt);
        }
        else if (evt.getSource() == metalMenuItem) {
            GaroePlaygroundGUI.this.metalMenuItemActionPerformed(evt);
        }
        else if (evt.getSource() == nimbusMenuItem) {
            GaroePlaygroundGUI.this.nimbusMenuItemActionPerformed(evt);
        }
        else if (evt.getSource() == cdemotifMenuItem) {
            GaroePlaygroundGUI.this.cdemotifMenuItemActionPerformed(evt);
        }
        else if (evt.getSource() == windowsMenuItem) {
            GaroePlaygroundGUI.this.windowsMenuItemActionPerformed(evt);
        }
        else if (evt.getSource() == winclassicMenuItem) {
            GaroePlaygroundGUI.this.winclassicMenuItemActionPerformed(evt);
        }
        else if (evt.getSource() == jButton1) {
            GaroePlaygroundGUI.this.jButton1ActionPerformed(evt);
        }
    }

    public void mouseClicked(java.awt.event.MouseEvent evt) {
    }

    public void mouseEntered(java.awt.event.MouseEvent evt) {
        if (evt.getSource() == reversi) {
            GaroePlaygroundGUI.this.reversiMouseEntered(evt);
        }
        else if (evt.getSource() == floodit) {
            GaroePlaygroundGUI.this.flooditMouseEntered(evt);
        }
        else if (evt.getSource() == jButton1) {
            GaroePlaygroundGUI.this.jButton1MouseEntered(evt);
        }
    }

    public void mouseExited(java.awt.event.MouseEvent evt) {
    }

    public void mousePressed(java.awt.event.MouseEvent evt) {
    }

    public void mouseReleased(java.awt.event.MouseEvent evt) {
    }// </editor-fold>//GEN-END:initComponents

    private void reversiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reversiMouseEntered
        this.gameImage.setIcon(new ImageIcon(System.class.getResource("/images/reversi.jpg")));
        this.gameInfo.setText("        Reversi\n\nReglas:\nA un jugador se le asigna un color y se dice que lleva las fichas de ese color, lo mismo para el adversario con el otro color.\n\nLos jugadores deben hacer un movimiento por turno, a menos que no se pueda hacer ninguno, pasando en ese caso el turno del jugador contrario.\n\nEl movimiento consiste en colocar una ficha de forma que flanquee una o varias fichas del color contrario y voltear esas fichas para que pasen a mostrar el propio color. Para que las fichas estén flanqueadas, deben formar una línea continua recta (diagonal u ortogonal) de fichas del mismo color entre dos fichas del color contrario (una de ellas la recién colocada y la otra ya presente. ");
    }//GEN-LAST:event_reversiMouseEntered

    private void flooditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_flooditMouseEntered
        this.gameImage.setIcon(new ImageIcon(System.class.getResource("/images/floodit.jpg")));
        this.gameInfo.setText("        Flood-it!\n\nReglas:\nPrimero se empieza seleccionado uno de los colores del menú.\n\nEl color de la zona cambiara y se extenderá a los espacios adyacentes que tenga el mismo color seleccionado, por lo que podrás cubrir zonas del tablero.\n\nEl objetivo del juego es cubrir todo el tablero de un mismo color en a lo sumo 25 pasos.");
    }//GEN-LAST:event_flooditMouseEntered

    private void reversiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reversiActionPerformed
        this.controller.startReversi();
    }//GEN-LAST:event_reversiActionPerformed

    private void flooditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flooditActionPerformed
        this.controller.startFloodit();
    }//GEN-LAST:event_flooditActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        GaroePlaygroundAbout about = new GaroePlaygroundAbout(this,true);
        about.setVisible(true);
        about.setEnabled(true);
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    private void metalMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_metalMenuItemActionPerformed
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FlooditGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FlooditGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FlooditGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FlooditGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        this.repaint();
    }//GEN-LAST:event_metalMenuItemActionPerformed

    private void nimbusMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nimbusMenuItemActionPerformed
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FlooditGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FlooditGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FlooditGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FlooditGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        this.repaint();
    }//GEN-LAST:event_nimbusMenuItemActionPerformed

    private void cdemotifMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdemotifMenuItemActionPerformed
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("CDE/Motif".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FlooditGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FlooditGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FlooditGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FlooditGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        this.repaint();
    }//GEN-LAST:event_cdemotifMenuItemActionPerformed

    private void windowsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_windowsMenuItemActionPerformed
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FlooditGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FlooditGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FlooditGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FlooditGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        this.repaint();
    }//GEN-LAST:event_windowsMenuItemActionPerformed

    private void winclassicMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_winclassicMenuItemActionPerformed
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows Classic".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FlooditGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FlooditGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FlooditGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FlooditGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        this.repaint();
    }//GEN-LAST:event_winclassicMenuItemActionPerformed

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        this.gameImage.setIcon(new ImageIcon(System.class.getResource("/images/jarrasagua.jpg")));
        this.gameInfo.setText("        Jarras de agua\n\nReglas:\nHay dos jarras de agua, cada una\ncon una capacidad fija.\nEl objetivo es lograr que las\njarras terminen con un cierto\ncontenido de agua aplicando\nsolamente las siguientes\nacciones:\n\n1) vaciar una jarra\n2) llenar una jarra\n3) transferir el contenido\n   de una jarra a la otra");
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.controller.startWaterJars();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GaroePlaygroundGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GaroePlaygroundGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GaroePlaygroundGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GaroePlaygroundGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new GaroePlaygroundGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem cdemotifMenuItem;
    private javax.swing.JMenuItem exitButton;
    private javax.swing.JButton floodit;
    private javax.swing.JLabel gameImage;
    private javax.swing.JTextPane gameInfo;
    private javax.swing.JPanel gamesPanel;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu lookNfeel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem metalMenuItem;
    private javax.swing.JMenuItem nimbusMenuItem;
    private javax.swing.JButton reversi;
    private javax.swing.JMenuItem winclassicMenuItem;
    private javax.swing.JMenuItem windowsMenuItem;
    // End of variables declaration//GEN-END:variables
}
